/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AdminDashboard {
    }
    interface AdminHome {
    }
    interface AdminLogin {
    }
    interface AdminReport {
    }
    interface AdminSignup {
    }
    interface AdminStudent {
        "s_address": string;
        "s_dob": string;
        "s_fname": string;
        "s_gender": string;
        "s_id": string;
        "s_lname": string;
        "s_phone": string;
        "s_section": string;
    }
    interface AdminStudentShow {
    }
    interface AdminSubject {
        "subject_name": string;
        "teacher_name": string;
    }
    interface AdminSubjectShow {
    }
    interface AdminTeacher {
        "t_address": string;
        "t_degree": string;
        "t_email": string;
        "t_experience": string;
        "t_gender": string;
        "t_id": string;
        "t_name": string;
        "t_phone": string;
    }
    interface AdminTeacherShow {
    }
    interface LibeRouter {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface StudentAttendance {
    }
    interface StudentBackground {
    }
    interface StudentHome {
    }
    interface StudentLogin {
    }
    interface StudentProfile {
    }
    interface StudentReport {
    }
    interface StudentSignup {
    }
    interface TeacherBackground {
    }
    interface TeacherHome {
    }
    interface TeacherLogin {
    }
    interface TeacherProfile {
    }
    interface TeacherReport {
    }
    interface TeacherSignup {
    }
    interface TeacherStudent {
    }
    interface TotalReport {
    }
}
declare global {
    interface HTMLAdminDashboardElement extends Components.AdminDashboard, HTMLStencilElement {
    }
    var HTMLAdminDashboardElement: {
        prototype: HTMLAdminDashboardElement;
        new (): HTMLAdminDashboardElement;
    };
    interface HTMLAdminHomeElement extends Components.AdminHome, HTMLStencilElement {
    }
    var HTMLAdminHomeElement: {
        prototype: HTMLAdminHomeElement;
        new (): HTMLAdminHomeElement;
    };
    interface HTMLAdminLoginElement extends Components.AdminLogin, HTMLStencilElement {
    }
    var HTMLAdminLoginElement: {
        prototype: HTMLAdminLoginElement;
        new (): HTMLAdminLoginElement;
    };
    interface HTMLAdminReportElement extends Components.AdminReport, HTMLStencilElement {
    }
    var HTMLAdminReportElement: {
        prototype: HTMLAdminReportElement;
        new (): HTMLAdminReportElement;
    };
    interface HTMLAdminSignupElement extends Components.AdminSignup, HTMLStencilElement {
    }
    var HTMLAdminSignupElement: {
        prototype: HTMLAdminSignupElement;
        new (): HTMLAdminSignupElement;
    };
    interface HTMLAdminStudentElement extends Components.AdminStudent, HTMLStencilElement {
    }
    var HTMLAdminStudentElement: {
        prototype: HTMLAdminStudentElement;
        new (): HTMLAdminStudentElement;
    };
    interface HTMLAdminStudentShowElement extends Components.AdminStudentShow, HTMLStencilElement {
    }
    var HTMLAdminStudentShowElement: {
        prototype: HTMLAdminStudentShowElement;
        new (): HTMLAdminStudentShowElement;
    };
    interface HTMLAdminSubjectElement extends Components.AdminSubject, HTMLStencilElement {
    }
    var HTMLAdminSubjectElement: {
        prototype: HTMLAdminSubjectElement;
        new (): HTMLAdminSubjectElement;
    };
    interface HTMLAdminSubjectShowElement extends Components.AdminSubjectShow, HTMLStencilElement {
    }
    var HTMLAdminSubjectShowElement: {
        prototype: HTMLAdminSubjectShowElement;
        new (): HTMLAdminSubjectShowElement;
    };
    interface HTMLAdminTeacherElement extends Components.AdminTeacher, HTMLStencilElement {
    }
    var HTMLAdminTeacherElement: {
        prototype: HTMLAdminTeacherElement;
        new (): HTMLAdminTeacherElement;
    };
    interface HTMLAdminTeacherShowElement extends Components.AdminTeacherShow, HTMLStencilElement {
    }
    var HTMLAdminTeacherShowElement: {
        prototype: HTMLAdminTeacherShowElement;
        new (): HTMLAdminTeacherShowElement;
    };
    interface HTMLLibeRouterElement extends Components.LibeRouter, HTMLStencilElement {
    }
    var HTMLLibeRouterElement: {
        prototype: HTMLLibeRouterElement;
        new (): HTMLLibeRouterElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLStudentAttendanceElement extends Components.StudentAttendance, HTMLStencilElement {
    }
    var HTMLStudentAttendanceElement: {
        prototype: HTMLStudentAttendanceElement;
        new (): HTMLStudentAttendanceElement;
    };
    interface HTMLStudentBackgroundElement extends Components.StudentBackground, HTMLStencilElement {
    }
    var HTMLStudentBackgroundElement: {
        prototype: HTMLStudentBackgroundElement;
        new (): HTMLStudentBackgroundElement;
    };
    interface HTMLStudentHomeElement extends Components.StudentHome, HTMLStencilElement {
    }
    var HTMLStudentHomeElement: {
        prototype: HTMLStudentHomeElement;
        new (): HTMLStudentHomeElement;
    };
    interface HTMLStudentLoginElement extends Components.StudentLogin, HTMLStencilElement {
    }
    var HTMLStudentLoginElement: {
        prototype: HTMLStudentLoginElement;
        new (): HTMLStudentLoginElement;
    };
    interface HTMLStudentProfileElement extends Components.StudentProfile, HTMLStencilElement {
    }
    var HTMLStudentProfileElement: {
        prototype: HTMLStudentProfileElement;
        new (): HTMLStudentProfileElement;
    };
    interface HTMLStudentReportElement extends Components.StudentReport, HTMLStencilElement {
    }
    var HTMLStudentReportElement: {
        prototype: HTMLStudentReportElement;
        new (): HTMLStudentReportElement;
    };
    interface HTMLStudentSignupElement extends Components.StudentSignup, HTMLStencilElement {
    }
    var HTMLStudentSignupElement: {
        prototype: HTMLStudentSignupElement;
        new (): HTMLStudentSignupElement;
    };
    interface HTMLTeacherBackgroundElement extends Components.TeacherBackground, HTMLStencilElement {
    }
    var HTMLTeacherBackgroundElement: {
        prototype: HTMLTeacherBackgroundElement;
        new (): HTMLTeacherBackgroundElement;
    };
    interface HTMLTeacherHomeElement extends Components.TeacherHome, HTMLStencilElement {
    }
    var HTMLTeacherHomeElement: {
        prototype: HTMLTeacherHomeElement;
        new (): HTMLTeacherHomeElement;
    };
    interface HTMLTeacherLoginElement extends Components.TeacherLogin, HTMLStencilElement {
    }
    var HTMLTeacherLoginElement: {
        prototype: HTMLTeacherLoginElement;
        new (): HTMLTeacherLoginElement;
    };
    interface HTMLTeacherProfileElement extends Components.TeacherProfile, HTMLStencilElement {
    }
    var HTMLTeacherProfileElement: {
        prototype: HTMLTeacherProfileElement;
        new (): HTMLTeacherProfileElement;
    };
    interface HTMLTeacherReportElement extends Components.TeacherReport, HTMLStencilElement {
    }
    var HTMLTeacherReportElement: {
        prototype: HTMLTeacherReportElement;
        new (): HTMLTeacherReportElement;
    };
    interface HTMLTeacherSignupElement extends Components.TeacherSignup, HTMLStencilElement {
    }
    var HTMLTeacherSignupElement: {
        prototype: HTMLTeacherSignupElement;
        new (): HTMLTeacherSignupElement;
    };
    interface HTMLTeacherStudentElement extends Components.TeacherStudent, HTMLStencilElement {
    }
    var HTMLTeacherStudentElement: {
        prototype: HTMLTeacherStudentElement;
        new (): HTMLTeacherStudentElement;
    };
    interface HTMLTotalReportElement extends Components.TotalReport, HTMLStencilElement {
    }
    var HTMLTotalReportElement: {
        prototype: HTMLTotalReportElement;
        new (): HTMLTotalReportElement;
    };
    interface HTMLElementTagNameMap {
        "admin-dashboard": HTMLAdminDashboardElement;
        "admin-home": HTMLAdminHomeElement;
        "admin-login": HTMLAdminLoginElement;
        "admin-report": HTMLAdminReportElement;
        "admin-signup": HTMLAdminSignupElement;
        "admin-student": HTMLAdminStudentElement;
        "admin-student-show": HTMLAdminStudentShowElement;
        "admin-subject": HTMLAdminSubjectElement;
        "admin-subject-show": HTMLAdminSubjectShowElement;
        "admin-teacher": HTMLAdminTeacherElement;
        "admin-teacher-show": HTMLAdminTeacherShowElement;
        "libe-router": HTMLLibeRouterElement;
        "my-component": HTMLMyComponentElement;
        "student-attendance": HTMLStudentAttendanceElement;
        "student-background": HTMLStudentBackgroundElement;
        "student-home": HTMLStudentHomeElement;
        "student-login": HTMLStudentLoginElement;
        "student-profile": HTMLStudentProfileElement;
        "student-report": HTMLStudentReportElement;
        "student-signup": HTMLStudentSignupElement;
        "teacher-background": HTMLTeacherBackgroundElement;
        "teacher-home": HTMLTeacherHomeElement;
        "teacher-login": HTMLTeacherLoginElement;
        "teacher-profile": HTMLTeacherProfileElement;
        "teacher-report": HTMLTeacherReportElement;
        "teacher-signup": HTMLTeacherSignupElement;
        "teacher-student": HTMLTeacherStudentElement;
        "total-report": HTMLTotalReportElement;
    }
}
declare namespace LocalJSX {
    interface AdminDashboard {
    }
    interface AdminHome {
    }
    interface AdminLogin {
    }
    interface AdminReport {
    }
    interface AdminSignup {
    }
    interface AdminStudent {
        "s_address"?: string;
        "s_dob"?: string;
        "s_fname"?: string;
        "s_gender"?: string;
        "s_id"?: string;
        "s_lname"?: string;
        "s_phone"?: string;
        "s_section"?: string;
    }
    interface AdminStudentShow {
    }
    interface AdminSubject {
        "subject_name"?: string;
        "teacher_name"?: string;
    }
    interface AdminSubjectShow {
    }
    interface AdminTeacher {
        "t_address"?: string;
        "t_degree"?: string;
        "t_email"?: string;
        "t_experience"?: string;
        "t_gender"?: string;
        "t_id"?: string;
        "t_name"?: string;
        "t_phone"?: string;
    }
    interface AdminTeacherShow {
    }
    interface LibeRouter {
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface StudentAttendance {
    }
    interface StudentBackground {
    }
    interface StudentHome {
    }
    interface StudentLogin {
    }
    interface StudentProfile {
    }
    interface StudentReport {
    }
    interface StudentSignup {
    }
    interface TeacherBackground {
    }
    interface TeacherHome {
    }
    interface TeacherLogin {
    }
    interface TeacherProfile {
    }
    interface TeacherReport {
    }
    interface TeacherSignup {
    }
    interface TeacherStudent {
    }
    interface TotalReport {
    }
    interface IntrinsicElements {
        "admin-dashboard": AdminDashboard;
        "admin-home": AdminHome;
        "admin-login": AdminLogin;
        "admin-report": AdminReport;
        "admin-signup": AdminSignup;
        "admin-student": AdminStudent;
        "admin-student-show": AdminStudentShow;
        "admin-subject": AdminSubject;
        "admin-subject-show": AdminSubjectShow;
        "admin-teacher": AdminTeacher;
        "admin-teacher-show": AdminTeacherShow;
        "libe-router": LibeRouter;
        "my-component": MyComponent;
        "student-attendance": StudentAttendance;
        "student-background": StudentBackground;
        "student-home": StudentHome;
        "student-login": StudentLogin;
        "student-profile": StudentProfile;
        "student-report": StudentReport;
        "student-signup": StudentSignup;
        "teacher-background": TeacherBackground;
        "teacher-home": TeacherHome;
        "teacher-login": TeacherLogin;
        "teacher-profile": TeacherProfile;
        "teacher-report": TeacherReport;
        "teacher-signup": TeacherSignup;
        "teacher-student": TeacherStudent;
        "total-report": TotalReport;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "admin-dashboard": LocalJSX.AdminDashboard & JSXBase.HTMLAttributes<HTMLAdminDashboardElement>;
            "admin-home": LocalJSX.AdminHome & JSXBase.HTMLAttributes<HTMLAdminHomeElement>;
            "admin-login": LocalJSX.AdminLogin & JSXBase.HTMLAttributes<HTMLAdminLoginElement>;
            "admin-report": LocalJSX.AdminReport & JSXBase.HTMLAttributes<HTMLAdminReportElement>;
            "admin-signup": LocalJSX.AdminSignup & JSXBase.HTMLAttributes<HTMLAdminSignupElement>;
            "admin-student": LocalJSX.AdminStudent & JSXBase.HTMLAttributes<HTMLAdminStudentElement>;
            "admin-student-show": LocalJSX.AdminStudentShow & JSXBase.HTMLAttributes<HTMLAdminStudentShowElement>;
            "admin-subject": LocalJSX.AdminSubject & JSXBase.HTMLAttributes<HTMLAdminSubjectElement>;
            "admin-subject-show": LocalJSX.AdminSubjectShow & JSXBase.HTMLAttributes<HTMLAdminSubjectShowElement>;
            "admin-teacher": LocalJSX.AdminTeacher & JSXBase.HTMLAttributes<HTMLAdminTeacherElement>;
            "admin-teacher-show": LocalJSX.AdminTeacherShow & JSXBase.HTMLAttributes<HTMLAdminTeacherShowElement>;
            "libe-router": LocalJSX.LibeRouter & JSXBase.HTMLAttributes<HTMLLibeRouterElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "student-attendance": LocalJSX.StudentAttendance & JSXBase.HTMLAttributes<HTMLStudentAttendanceElement>;
            "student-background": LocalJSX.StudentBackground & JSXBase.HTMLAttributes<HTMLStudentBackgroundElement>;
            "student-home": LocalJSX.StudentHome & JSXBase.HTMLAttributes<HTMLStudentHomeElement>;
            "student-login": LocalJSX.StudentLogin & JSXBase.HTMLAttributes<HTMLStudentLoginElement>;
            "student-profile": LocalJSX.StudentProfile & JSXBase.HTMLAttributes<HTMLStudentProfileElement>;
            "student-report": LocalJSX.StudentReport & JSXBase.HTMLAttributes<HTMLStudentReportElement>;
            "student-signup": LocalJSX.StudentSignup & JSXBase.HTMLAttributes<HTMLStudentSignupElement>;
            "teacher-background": LocalJSX.TeacherBackground & JSXBase.HTMLAttributes<HTMLTeacherBackgroundElement>;
            "teacher-home": LocalJSX.TeacherHome & JSXBase.HTMLAttributes<HTMLTeacherHomeElement>;
            "teacher-login": LocalJSX.TeacherLogin & JSXBase.HTMLAttributes<HTMLTeacherLoginElement>;
            "teacher-profile": LocalJSX.TeacherProfile & JSXBase.HTMLAttributes<HTMLTeacherProfileElement>;
            "teacher-report": LocalJSX.TeacherReport & JSXBase.HTMLAttributes<HTMLTeacherReportElement>;
            "teacher-signup": LocalJSX.TeacherSignup & JSXBase.HTMLAttributes<HTMLTeacherSignupElement>;
            "teacher-student": LocalJSX.TeacherStudent & JSXBase.HTMLAttributes<HTMLTeacherStudentElement>;
            "total-report": LocalJSX.TotalReport & JSXBase.HTMLAttributes<HTMLTotalReportElement>;
        }
    }
}
